import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Best info helper",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
        <body className="min-h-full flex flex-col">
        <main className="relative min-h-screen overflow-hidden bg-[#f8e4da]">
            <div
                className="absolute inset-0 bg-cover bg-center bg-no-repeat"
                style={{
                    backgroundImage: "url('/background.png')",
                }}
            />

            <div className="absolute inset-0 bg-[#1a1333]/40"/>

            <div className="relative z-10">
                <nav className="mx-auto flex max-w-7xl items-center justify-between px-6 py-6 cursor-pointer">
                    <Link href={"/"}><div className="flex items-center gap-2 font-semibold">
                        <div className="flex h-8 w-8 items-center justify-center rounded-full bg-[#111827] text-white">
                            ⌖
                        </div>
                        AddressHub
                    </div>
                    </Link>
                    <div className="hidden items-center gap-10 text-sm md:flex">
                        <Link href={'/highlights'}>Features</Link>
                        <Link href={'/how-it-works'}>How it works</Link>
                        <Link href={'/about'}>About</Link>
                        <Link href={'/contact'}>Contact</Link>
                    </div>

                    <button
                        className="rounded-xl bg-[#111827] px-5 py-3 text-sm font-medium text-white shadow-lg transition hover:scale-105 cursor-pointer">
                        <Link href={'/dashboard'}>Get Started</Link>
                    </button>
                </nav>

                {children}
            </div>
        </main>
        </body>

        </html>
    );
}
